In [9]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

fil = np.array([[2,4,6],
            [1,2,3],
            [5,10,15]])
hor = np.zeros((3,1))
for i in range (3):
    hor[i] = [fil[i][0]]

ven = fil[1]
print("filter matrix is \n %s" %fil)
print("The Lx1 matrix is \n %s" %hor)
print("The 1xL matrix is %s" %fil[1])

filter matrix is 
 [[ 2  4  6]
 [ 1  2  3]
 [ 5 10 15]]
The Lx1 matrix is 
 [[2.]
 [1.]
 [5.]]
The 1xL matrix is [1 2 3]


In [26]:
img = cv2.imread('brain.jpeg', cv2.IMREAD_GRAYSCALE).astype(float) 

def filter_img_size(img_shape, kernel_size: int):
    # Initializing the number of pixels in each axis
    num_pix_y = 0
    num_pix_x = 0

    for i in range(img_shape[0]):
        added = i + kernel_size
        if added <= img_shape[0]:
            num_pix_y += 1

    for j in range(img_shape[1]):
        added = j + kernel_size
        if added <= img_shape[1]:
            num_pix_x += 1

    return (num_pix_y, num_pix_x)

def convol(img: np.array, kernel: np.array):
    sqr_size = filter_img_size(
        img_shape=img.shape,
        kernel_size=kernel.shape[0]
    )
    k = kernel.shape[0]
    convol_img = np.zeros(img.shape)
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            mat = img[i:i+k, j]
            convol_img[i, j] = np.sum(np.multiply(mat, kernel))

    return convol_img

def convol2(img: np.array, kernel: np.array):
    sqr_size = filter_img_size(
        img_shape=img.shape,
        kernel_size=kernel.shape[0]
    )
    k = kernel.shape[0]
    convol_img = np.zeros(img.shape)
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            mat = img[i, j]
            convol_img[i, j] = np.sum(np.multiply(mat, kernel))

    return convol_img

hor_img = convol(img=img, kernel=hor)
fil_img = convol2(img=hor_img, kernel=ven)
cv2.imshow("result",fil_img)
cv2.waitKey(0)

-1